name: carp_study_app
description: The generic CARP study app.
publish_to: "none"
version: 2.1.1+37

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^2.0.0
  carp_core: ^1.8.0
  carp_mobile_sensing: ^1.11.4
  carp_context_package: ^1.10.0
  carp_connectivity_package: ^1.7.0
  carp_survey_package: ^1.8.2
  carp_audio_package: ^1.8.0
  carp_esense_package: ^1.6.0
  carp_polar_package: ^1.6.0
  carp_health_package: ^2.11.0
  carp_movesense_package: ^1.6.0

  carp_webservices: ^3.5.0
  carp_backend: ^1.9.1

  research_package: ^1.7.2
  cognition_package: ^1.6.1

  flutter_launcher_icons: ^0.14.0
  url_launcher: ^6.1.5
  timeago: ^3.1.0
  expandable: ^5.0.1
  flutter_markdown: ^0.7.0
  camera: ^0.11.0
  video_player: ^2.2.7
  path_provider: ^2.0.2
  json_annotation: ^4.4.0
  open_settings: ^2.0.0

  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.69.0
  google_fonts: ^6.1.0
  go_router: ^14.0.0
  flutter_svg: ^2.0.4
  flutter_blue_plus: ^1.15.5
  intl: ">=0.18.0 <0.20.0"
  permission_handler: ^11.0.1
  connectivity_plus: ^6.0.0
  open_settings_plus: ^0.3.0
  appcheck: ^1.5.2

# Overriding carp libraries to use the local copy
dependency_overrides:
  # carp_serializable:
  #   path: ../carp/carp.sensing-flutter/carp_serializable/
  # carp_core:
  #   path: ../carp/carp.sensing-flutter/carp_core/
  # carp_mobile_sensing:
  #   path: ../carp/carp.sensing-flutter/carp_mobile_sensing/
  # carp_context_package:
  #   path: ../carp/carp.sensing-flutter/packages/carp_context_package/
  # carp_connectivity_package:
  #   path: ../../packages/carp_connectivity_package/
  # carp_survey_package:
  #   path: ../carp/carp.sensing-flutter/packages/carp_survey_package/
  # carp_communication_package:
  #   path: ../../packages/carp_communication_package/
  # carp_audio_package:
  #   path: ../carp/carp.sensing-flutter/packages/carp_audio_package/
  # carp_apps_package:
  #   path: ../../packages/carp_apps_package/
  # carp_esense_package:
  #   path: ../../packages/carp_esense_package/
  # carp_polar_package:
  #   path: ../carp/carp.sensing-flutter/packages/carp_polar_package/
  # carp_movisens_package:
  #   path: ../../packages/carp_movisens_package/
  # carp_health_package:
  #   path: ../carp/carp.sensing-flutter/packages/carp_health_package/
  # carp_movesense_package:
  #   path: ../carp.sensing-flutter/packages/carp_movesense_package/

  # carp_webservices:
  #   path: ../carp/carp.sensing-flutter/backends/carp_webservices/
  # carp_backend:
  #   path: ../carp/carp.sensing-flutter/backends/carp_backend/

  # research_package: 
  #   path: ../research.package/

dev_dependencies:
  test: any
  json_serializable: any
  build_runner: any
  flutter_test:
    sdk: flutter
  mockito: any
  flutter_lints: any

# Is used to change the default app launch icons on iOS and Android.
# To install:
#  1. import the 'flutter_launcher_icons' package above
#  2. add the 'flutter_icons:' section below
#  3. run 'flutter pub get'
#  3. run 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/instructions/
    - assets/instructions/en/
    - assets/instructions/da/
    - assets/icons/
    - assets/lang/
    - assets/carp/lang/
    - assets/carp/resources/
    - assets/carp/messages/
    - assets/images/messages/
    - assets/carp_logo.png
    - assets/logo.png

  #  auto generate json code (.g files) with:
  #    dart run build_runner build --delete-conflicting-outputs
