name: carp_study_app
description: The generic CARP study app.
publish_to: 'none'
version: 0.40.3

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.0.0
  # carp_mobile_sensing: ^0.40.3
  # carp_context_package: ^0.40.0
  # carp_survey_package: ^0.40.0
  # carp_audio_package: ^0.40.0
  # carp_backend: ^0.40.0
  # carp_esense_package: ^0.40.0
  # carp_polar_package: ^0.40.0
  carp_health_package: ^2.4.0

  research_package: ^1.2.0
  cognition_package: ^1.3.2

  flutter_launcher_icons: ^0.10.0
  url_launcher: ^6.1.5
  timeago: ^3.1.0
  expandable: ^5.0.1
  charts_flutter: ^0.12.0
  intl: ^0.17.0
  flutter_markdown: ^0.6.4
  camera: ^0.10.0
  video_player: ^2.2.7
  path_provider: ^2.0.2
  json_annotation: ^4.4.0
  app_settings: ^4.1.5
  flutter_blue_plus: ^1.1.2
  esense_flutter: ^0.6.2
  open_settings: ^2.0.0

  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.55.2
  google_fonts: ^3.0.1

dependency_overrides:
  carp_core:
    git:
      url: https://github.com/cph-cachet/carp.sensing-flutter.git
      ref: develop
      path: carp_core
  carp_mobile_sensing:
    git:
      url: https://github.com/cph-cachet/carp.sensing-flutter.git
      ref: develop
      path: carp_mobile_sensing
  carp_context_package:
    git:
      url: https://github.com/cph-cachet/carp.sensing-flutter.git
      ref: develop
      path: packages/carp_context_package/
  carp_survey_package:
    git:
      url: https://github.com/cph-cachet/carp.sensing-flutter.git
      ref: develop
      path: packages/carp_survey_package/
  # # carp_connectivity_package:
  # #   git:
  # #     url: https://github.com/cph-cachet/carp.sensing-flutter.git
  # #     ref: develop
  # #     path: packages/carp_connectivity_package/
  carp_audio_package:
    git:
      url: https://github.com/cph-cachet/carp.sensing-flutter.git
      ref: develop
      path: packages/carp_audio_package/
  carp_esense_package:
    git:
      url: https://github.com/cph-cachet/carp.sensing-flutter.git
      ref: develop
      path: packages/carp_esense_package/
  carp_polar_package:
    git:
      url: https://github.com/cph-cachet/carp.sensing-flutter.git
      ref: develop
      path: packages/carp_polar_package/
  carp_backend:
    git:
      url: https://github.com/cph-cachet/carp.sensing-flutter.git
      ref: develop
      path: backends/carp_backend/
  carp_webservices:
    git:
      url: https://github.com/cph-cachet/carp.sensing-flutter.git
      ref: develop
      path: backends/carp_webservices/
  # research_package:
  #   git:
  #     url: https://github.com/cph-cachet/research.package.git
  #     ref: dev-carp-core-0_40_0
  # cognition_package:
  #   git:
  #     url: https://github.com/cph-cachet/cognition_package.git
  #     ref: develop


dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  #  auto generate json code (.g files) with:
  #    flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: any
  build_runner: any
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Is used to change the default app launch icons on iOS and Android.
# To install:
#  1. import the 'flutter_launcher_icons' package above
#  2. add the 'flutter_icons:' section below
#  3. run 'flutter pub get'
#  3. run 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/logo.png'
  # image_path: "assets/app_icon.png"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/images/messages/
    - assets/lang_local/
    - assets/carp_logo.png
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
