on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  apk:
    name: Create Release and Upload APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: |
            flutter
            ~/.pub-cache
          key: flutter-${{ hashFiles('**/pubspec.lock') }}

      - if: ${{ steps.cache-flutter.outputs.cache-hit != 'true' }}
        name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b stable $FOLDER

      - name: Add Flutter to PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - if: ${{ steps.cache-flutter.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: flutter pub get

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "$PLAY_STORE_CONFIG_JSON" > PLAY_STORE_CONFIG.json
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storeFile=upload-keystore.jks" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android

      - name: Print Flutter Version
        run: |
          flutter --version
          pwd
          
      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter pub upgrade
          flutter build apk --release --no-tree-shake-icons

      - name: Create Release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.ref }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: carp-studies-app-${{ github.ref_name }}.apk
          asset_content_type: application/vnd.android.package-archive
