on:
  push:
    tags:
      - 'v2.0.0'

name: Create Release

jobs:
  apk:
    name: Create Release and Upload APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: |
            flutter
            ~/.pub-cache
          key: flutter-${{ hashFiles('**/pubspec.lock') }}

      - if: ${{ steps.cache-flutter.outputs.cache-hit != 'true' }}
        name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b 3.19.6 $FOLDER

      - name: Add Flutter to PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - if: ${{ steps.cache-flutter.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: flutter pub get

      - name: Print Flutter Version
        run: |
          flutter --version
          pwd
      
      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter pub upgrade
          flutter build apk --release --no-tree-shake-icons
          pwd

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.ref }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/zip


      # - name: Upload APK to Release
      #   id: upload-release-asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: build/app/outputs/flutter-apk/app-release.apk
      #     asset_name: app-release.apk
      #     asset_content_type: application/vnd.android.package-archive


  # create-release:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@master

  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@latest
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  #         body: |
  #           Changes in this Release
  #           ${{ github.event.head_commit.message }}
  #         draft: false
  #         prerelease: false


  # upload-apk:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: AButler/upload-release-assets@v3.0
  #       with:
  #         files: "app/build/outputs/apk/release/app-release.apk"
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}