on:
  push:
    tags:
      - 'v2.0.0'

name: Create Release

jobs:
  apk:
    name: Create Release and Upload APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: |
            flutter
            ~/.pub-cache
          key: flutter-${{ hashFiles('**/pubspec.lock') }}

      - if: ${{ steps.cache-flutter.outputs.cache-hit != 'true' }}
        name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b 3.19.6 $FOLDER

      - name: Add Flutter to PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - if: ${{ steps.cache-flutter.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: flutter pub get

      - name: Print Flutter Version
        run: |
          flutter --version
          pwd
      
      - name: Build APK
        run: |
          sh "flutter clean"
          sh "flutter pub get"
          sh "flutter pub upgrade"
          sh "flutter build appbundle --release --no-deferred-components --no-tree-shake-icons"

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk


  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Create Release
        # id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false


  # upload-apk:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: AButler/upload-release-assets@v3.0
  #       with:
  #         files: "app/build/outputs/apk/release/app-release.apk"
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}