name: Deploy to Play Store production
on:
  # Enable manual run
  push:
    tags:
      - '*'


# Declare default permissions as read only.
permissions: read-all

jobs:
  workflow_run:
    uses: cph-cachet/carp.study-app/.github/workflows/deploy_play_store_workflow@master
