name: Deploy to Play Store production
on:
  release:
    types:
      - released
  workflow_dispatch:


# Declare default permissions as read only.
permissions: read-all

jobs:
  workflow_run:
    uses: cph-cachet/carp-studies-app/.github/workflows/deploy_play_store.yml@master
    secrets: inherit
    with:
      lane: 'promote_to_production'
