# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: flutter
          key: flutter-${{ hashFiles('**/pubspec.lock') }}
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b stable flutter

      - name: Add Flutter to Path
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed lib/**

      - name: Analyze project source
        run: flutter analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: flutter
          key: flutter-${{ hashFiles('**/pubspec.lock') }}
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH=`pwd`/flutter/bin:$PATH
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
